using System;
using System.Collections.Generic;
using System.Linq;
using IM.LifeCycle;
using UnityEngine;
using Random = UnityEngine.Random;

namespace IM.Map
{
    [Serializable]
    public class PropSpawnGroup
    {
        [Tooltip("Name for inspector organization.")]
        public string GroupName = "New Prop Group";
        
        [Header("Prefabs & Count")]
        public List<GameObject> Prefabs = new();
        [Min(0)] public int MinCount = 1;
        [Min(0)] public int MaxCount = 3;

        [Header("Size / Clearance")]
        [Tooltip("The grid footprint of this prop (e.g. 1x1, 2x2).")]
        public Vector2Int Size = new Vector2Int(1, 1);
        [Tooltip("Extra clearance radius from the center of the prop AFTER the footprint is reserved.")]
        [Min(0)] public float ClearanceRadius = 1.5f;

        [Header("Placement Weights (Edge vs Center)")]
        [Min(0)] public float EdgeThreshold = 1.5f;
        [Min(0)] public float EdgeBias = 10f;
        [Range(0, 1)] public float CenterWeight = 0.05f;

        [Header("Clustering")]
        [Tooltip("Should this group try to spawn near props generated by previous groups?")]
        public bool ClusterToPrevious = false;
        [Min(0)] public float ClusterRadius = 3f;
        [Tooltip("Multiplier applied to the weight if within the cluster radius.")]
        [Min(1)] public float ClusterBiasMultiplier = 8f;
    }

    public class RandomPropRoomDecorator : MonoBehaviour, IRoomDecorator
    {
        [Header("Global Settings")]
        [Tooltip("Minimum distance candidates must be from room ports.")]
        [SerializeField, Min(0)] private float _minPortClearance = 2f;
        [Tooltip("The grid resolution for potential spawn points (Should match your tile size, usually 1).")]
        [SerializeField, Min(0.1f)] private float _candidateStep = 1f;

        [Header("Generation Sequence")]
        [Tooltip("Evaluated from top to bottom. Place larger props first.")]
        [SerializeField] private List<PropSpawnGroup> _propGroups = new();

        private struct CandidatePlacement
        {
            public Vector2Int BottomLeftCell;
            public Vector2 WorldCenter;
        }

        public void Decorate(IGameObjectRoom room, IRoomShape shape, IGameObjectFactory factory)
        {
            if (shape == null || _propGroups == null || _propGroups.Count == 0) return;

            List<Vector2> portPositions = room.RoomPorts
                .OfType<MonoBehaviour>()
                .Select(mb => (Vector2)mb.transform.localPosition)
                .ToList();

            HashSet<Vector2Int> availableGrid = GenerateGridCandidates(portPositions, shape.Metrics);
            List<Vector2> allPreviousSpawns = new();

            foreach (PropSpawnGroup group in _propGroups)
            {
                if (group.Prefabs == null || group.Prefabs.Count == 0) continue;

                int targetCount = Random.Range(group.MinCount, group.MaxCount + 1);
                List<Vector2> currentGroupSpawns = new();

                for (int i = 0; i < targetCount; i++)
                {
                    List<CandidatePlacement> validCandidates = new();

                    foreach (Vector2Int cell in availableGrid)
                    {
                        if (DoesPropFitOnGrid(cell, group.Size, availableGrid))
                        {
                            Vector2 worldPos = GetPropWorldPosition(cell, group.Size, shape.Metrics);

                            if (IsPropInsideShape(worldPos, group.Size, shape.Metrics))
                            {
                                validCandidates.Add(new CandidatePlacement { BottomLeftCell = cell, WorldCenter = worldPos });
                            }
                        }
                    }

                    if (validCandidates.Count == 0) break;

                    float[] weights = validCandidates.Select(c => GetCandidateWeight(c.WorldCenter, shape.Metrics, group, allPreviousSpawns)).ToArray();
                    int chosenIndex = GetWeightedRandomIndex(weights);
                    var chosenPlacement = validCandidates[chosenIndex];
                    
                    GameObject prefabToSpawn = GetRandomProp(group.Prefabs);
                    if (prefabToSpawn)
                    {
                        SpawnProp(prefabToSpawn, chosenPlacement.WorldCenter, room, factory);
                        currentGroupSpawns.Add(chosenPlacement.WorldCenter);
                    }

                    ConsumeGridTiles(chosenPlacement, group, availableGrid, shape.Metrics);
                }

                allPreviousSpawns.AddRange(currentGroupSpawns);
            }
        }

        /// <summary>
        /// Generates a master list of all integer grid coordinates inside the room bounds.
        /// </summary>
        private HashSet<Vector2Int> GenerateGridCandidates(List<Vector2> portPositions, ShapeMetrics metrics)
        {
            HashSet<Vector2Int> grid = new();

            int gridWidth = Mathf.CeilToInt(metrics.TotalW / _candidateStep);
            int gridHeight = Mathf.CeilToInt(metrics.TotalH / _candidateStep);

            for (int x = 0; x < gridWidth; x++)
            {
                for (int y = 0; y < gridHeight; y++)
                {
                    Vector2Int cell = new Vector2Int(x, y);
                    Vector2 cellCenter = GetCellCenter(cell, metrics);

                    if (!metrics.IsInsideShape(cellCenter)) continue;
                    if (portPositions.Any(pp => Vector2.Distance(cellCenter, pp) < _minPortClearance)) continue;

                    grid.Add(cell);
                }
            }
            return grid;
        }

        /// <summary>
        /// Calculates the perfectly aligned center point for the prefab based on its footprint size.
        /// </summary>
        private Vector2 GetPropWorldPosition(Vector2Int bottomLeftCell, Vector2Int size, ShapeMetrics metrics)
        {
            float centerX = metrics.RoomOriginX + (bottomLeftCell.x + (size.x * 0.5f)) * _candidateStep;
            float centerY = metrics.RoomOriginY + (bottomLeftCell.y + (size.y * 0.5f)) * _candidateStep;
            return new Vector2(centerX, centerY);
        }

        private Vector2 GetCellCenter(Vector2Int cell, ShapeMetrics metrics)
        {
            return new Vector2(
                metrics.RoomOriginX + (cell.x + 0.5f) * _candidateStep,
                metrics.RoomOriginY + (cell.y + 0.5f) * _candidateStep
            );
        }

        /// <summary>
        /// Checks if ALL tiles in the required WxH footprint are currently available.
        /// </summary>
        private bool DoesPropFitOnGrid(Vector2Int bottomLeftCell, Vector2Int size, HashSet<Vector2Int> availableGrid)
        {
            for (int i = 0; i < size.x; i++)
            {
                for (int j = 0; j < size.y; j++)
                {
                    if (!availableGrid.Contains(new Vector2Int(bottomLeftCell.x + i, bottomLeftCell.y + j)))
                        return false;
                }
            }
            return true;
        }

        private bool IsPropInsideShape(Vector2 worldCenter, Vector2Int size, ShapeMetrics metrics)
        {
            float halfW = (size.x * _candidateStep) * 0.5f;
            float halfH = (size.y * _candidateStep) * 0.5f;

            Vector2 topRight = new Vector2(worldCenter.x + halfW, worldCenter.y + halfH);
            Vector2 topLeft = new Vector2(worldCenter.x - halfW, worldCenter.y + halfH);
            Vector2 bottomRight = new Vector2(worldCenter.x + halfW, worldCenter.y - halfH);
            Vector2 bottomLeft = new Vector2(worldCenter.x - halfW, worldCenter.y - halfH);

            return metrics.IsInsideShape(topRight) && 
                   metrics.IsInsideShape(topLeft) && 
                   metrics.IsInsideShape(bottomRight) && 
                   metrics.IsInsideShape(bottomLeft);
        }

        /// <summary>
        /// Removes the footprint tiles from the master grid so they can't be used again.
        /// Also processes additional clearance padding.
        /// </summary>
        private void ConsumeGridTiles(CandidatePlacement placement, PropSpawnGroup group, HashSet<Vector2Int> availableGrid, ShapeMetrics metrics)
        {
            for (int i = 0; i < group.Size.x; i++)
            {
                for (int j = 0; j < group.Size.y; j++)
                {
                    availableGrid.Remove(new Vector2Int(placement.BottomLeftCell.x + i, placement.BottomLeftCell.y + j));
                }
            }

            if (group.ClearanceRadius > 0)
            {
                List<Vector2Int> tilesToClear = new();
                foreach (Vector2Int cell in availableGrid)
                {
                    Vector2 cellCenter = GetCellCenter(cell, metrics);
                    if (Vector2.Distance(cellCenter, placement.WorldCenter) < group.ClearanceRadius)
                    {
                        tilesToClear.Add(cell);
                    }
                }

                foreach (Vector2Int cell in tilesToClear)
                {
                    availableGrid.Remove(cell);
                }
            }
        }

        private float GetCandidateWeight(Vector2 pos, ShapeMetrics metrics, PropSpawnGroup group, List<Vector2> previousSpawns)
        {
            float weight = metrics.GetEdgeDistance(pos) <= group.EdgeThreshold ? group.EdgeBias : group.CenterWeight;

            if (group.ClusterToPrevious && previousSpawns.Count > 0)
            {
                if (previousSpawns.Min(bp => Vector2.Distance(pos, bp)) <= group.ClusterRadius)
                {
                    weight *= group.ClusterBiasMultiplier;
                }
            }

            return weight;
        }

        private GameObject GetRandomProp(List<GameObject> props)
        {
            var validProps = props.Where(p => p).ToList();
            if (validProps.Count == 0) return null;
            return validProps[Random.Range(0, validProps.Count)];
        }

        private void SpawnProp(GameObject prefab, Vector2 localPos, IGameObjectRoom room, IGameObjectFactory factory)
        {
            GameObject go = factory.Create(prefab, false);
            room.Add(go);
            go.transform.localPosition = new Vector3(localPos.x, localPos.y, 0f);
        }

        private static int GetWeightedRandomIndex(float[] weights)
        {
            float total = 0f;
            foreach (float w in weights) total += w;
            if (total <= 0f) return Random.Range(0, weights.Length);

            float roll = Random.value * total;
            float cumulative = 0f;
            for (int i = 0; i < weights.Length; i++)
            {
                cumulative += weights[i];
                if (roll <= cumulative) return i;
            }
            return weights.Length - 1;
        }
    }
}